### ISSUE TITLE
Item Helper is creating Template also as a normal Item

### ISSUE THREAD

**Issue by palashjhabak** [techlift-tech/erpnext_retail#22]
Do the following test
create a item template manually and then create its variant
do the same using Item Helper

**Comment by surajTechlift** [comment]
@palashjhabak  item helper creates variants but not creating template

**Comment by palashjhabak** [comment]
@surajTechlift ok.

**Comment by palashjhabak** [comment]
@surajTechlift did you try to debug this?

**Comment by surajTechlift** [comment]
done
