### ISSUE TITLE
New Doctype for Price Based Tax Category Selection

### ISSUE THREAD

**Issue by palashjhabak** [techlift-tech/erpnext_retail#23]
Create a new Doctype called "Price Based Tax Category Selection" with following fields
1. Company - Link
2. For - Select with Options ("All", "Item Group", "Item")
3. Item Group - Visible only if "Item Group is selected in For"
4. Item - Visible only if "Item is selected in For"
5. Rule Child Table
    1. From Price (Including), To Price (Including), Tax Category

**Comment by surajTechlift** [comment]
![image](https://user-images.githubusercontent.com/49982705/71976815-43328680-323d-11ea-8170-c49f1582ff22.png)

**Comment by surajTechlift** [comment]
done
