### ISSUE TITLE
Tax Calculation in SI and PI based on new PRices based Tax Rules

### ISSUE THREAD

**Issue by palashjhabak** [techlift-tech/erpnext_retail#25]
Testing to be done:
1. Create 3 Items - 2 in same Item group and one in another item group
2. Selling Rate to be 500, 1001, 2000 respectively
3. Create a rule for Selling, All with range as 1-999 5%, 1000-1000000 12%
4. Create a rule for Item Group (group in which there are 2 items) with range 0-10000000 5%
5. Create a rule for one Item (one out of 2 in the same group) with range 0-999 12% 1000-1000000 5%
6. Create a Sales Invoice with all 3 items, submit and check tax calculation

**Comment by surajTechlift** [comment]
@palashjhabak  have tested all scenarios only problem is tax can be find in child table but does not reflect in the tax breakup
